import React from 'react'
import { SiteNav2 } from '../components'

const Introduction = () => {
  return (
	<div className='w-full h-auto bg-gradient-to-b from-white to-slate-100 dark:from-primary dark:to-gray-800 flex flex-row font-roboto pb-10 text-primary dark:text-white overflow-x-hidden'>
		<SiteNav2 />
		<div className='w-full h-auto flex flex-col justify-center pt-3 items-center'>
		<div className='w-full sm:w-[95%] h-auto mt-10 flex flex-col rounded-[20px] text-primary dark:text-white items-center justify-center font-roboto  '>
			<div className='w-full sm:w-[95%] flex flex-col items-start mb-10 '>
				<h1 className='w-fit h-fit py-4 text-[36px] bg-gradient-to-r dark:from-slate-600 from-slate-400 to-transparent rounded-[10px] flex text-left text-shadow-lightTitle dark:text-shadow-drop font-bold pl-5 pr-96 items-center'>Introduction</h1>
			</div>
			<div className='w-[90%] flex flex-col gap-5 text-lg text-left pb-20'>
				<h1 className='header-text w-fit min-w-[200px] text-3xl text-shadow-lightTitle dark:text-shadow-drop bg-gradient-to-r dark:from-slate-600 from-slate-400 to-transparent rounded-[5px] pl-2 pr-6 sm:pr-48'>What is Shapers of Mana?</h1>
				<p>Shapers of Mana is a high fantasy Tabletop Role Playing Game set in the lands of Noxstellus. Noxstellus is a sprawling continent home to many peoples and nations, where Mana flows through all living beings. While the origins and intricacies of Mana remain a mystery, many creatures have learned how to channel and control Mana to create magical spells capable of affecting themselves, others, and the world around them. People capable of directly controlling the Mana within their bodies are known as Mages, and by honing their abilities can become powerful enough to create truly awe-inspiring spells capable of affecting entire cities. Mages in Noxstellus take on many forms. Some enhance their bodies and minds with mana to improve their martial capabilities or transform parts of their bodies into those of other creatures. Others take direct control of the elements and forces of nature to create objects or conjure destructive effects. There are also those who weave their own Mana into the bodies of others, allowing them to quickly heal another's wounds or fool their senses with illusions.
					<br /><br />Throughout Noxstellus are scattered ruins, traces of a civilization long destroyed of which no records remain. While the ruins have puzzled magical researchers in the past, the recent invention of Manasteel has reignited interest in the ruins as the similarities between them and Manasteel constructs are strikingly apparent. Manasteel is a malleable metal capable of conducting mana as if it were a living being. While not able of producing its own mana, Manasteel can be molded into weapons or objects which can create magical effects even when used by untrained individuals, a feat impossible when working with normal materials. Some see the recent developments as a warning of what will happen should Manasteel be furthur developed, while others see it as an exciting opportunity to finally learn of the ancient civilization that has thusfar remained a complete mystery.
					<br /><br />In this time of innovation and evolution, players are given an opportunity to experience Noxstellus as members of the Shapers' Guild. The Shapers' Guild is an international organization of Mages, having a presence in almost every corner of the continent. Anyone in Noxstellus with a problem can request the aid of the Shapers' Guild, whether they be a peasant, merchant, soldier, or even king. When a request is made, guild officials will determine the difficulty of the request and post the job in their guild halls. Members of the Shaper's Guild, commonly called Shapers, grant their aid to complete these jobs in exchange for pay, fame, or increased status within the Guild. Shapers have a unique position, being given the freedom to travel across Noxstellus as they wish with the ability to find work through the Guild no matter where they go. Taking on the role of Shapers, players will have ample opportunity to journey the lands as they wish, or build up reputation and influence by making a single region their home.
					<br /><br />
				</p>
				<h1 className='header-text w-fit min-w-[200px] text-3xl text-shadow-lightTitle dark:text-shadow-drop bg-gradient-to-r dark:from-slate-600 from-slate-400 to-transparent rounded-[5px] pl-2 pr-6 sm:pr-48'>Getting Started</h1>
				<p>SoM follows the standard format for a TRPG, having a group of players roleplay through a scenario while guided by a narrator. The ultimate goal of playing SoM is to tell a story together, using the rules as a guideline to keep story elements consistent as well as progessing the overall narrative. One player in the group acts as the Game Master(GM). The GM is a guide and narrator for the other players; they shape the direction of the story being told by roleplaying as NPCs, describing scenes, and making rules decisions when necessary. Each other player takes control of a single character within the story, called a Player Character(PC). To design and customise their PCs, players follow the Character Creation Rules. The story largely follows the events surrounding the PCs and how they interact with those events. 
					<br /><br />A complete story from beginning to end is called a Campaign, which is broken up into Arcs, each of which is made up of several Sessions. A Session is a single "game day", typically lasting 3-4 hours. Each Session is made up of one or more Scenes, which are narratively distinct scenarios that the PCs find themselves in. Scenes can greatly vary in content; a Scene could follow the PCs as they roam around a new city, detail an intense negotiation between the party and a client, or resolve a conflict between one or more PCs and their adversaries. Some Scenes have a loose set of rules guiding them, while others have a more specific ruleset to properly guide the Scene's narrative.
					<br /><br />At the end of every Session, players earn Experience Points(XP) that they can spend to have their characters improve their abilities or learn new ones. There are two types of XP that characters earn, Standard Experience Points(SXP) and Magical Experience Points(MXP). Once they have earned and spent enough MXP, they become capable of increasing their Magic Grade(MG), a process that makes them significantly more competent in their areas of experitise. Characters increasing their MG is a lengthy process, and so is typically done between Arcs. The gaps between story Arcs give characters an opportunity to describe the pursuits and short term goals of their PCs narratively, rather than through roleplay. 
					<br /><br />  </p>
				<h1 className='header-text w-fit min-w-[200px] text-3xl text-shadow-lightTitle dark:text-shadow-drop bg-gradient-to-r dark:from-slate-600 from-slate-400 to-transparent rounded-[5px] pl-2 pr-6 sm:pr-48'>Playing SoM</h1>
				<p>To play SoM, the GM describes Scenes to the players, who will roleplay their Characters' actions within those Scenes. When a PC or NPC wants to perform a non-trivial action (something that they have a chance of failing, or where their performance on the action will influence the outcome of a sitation) they will need to make a Test. 
				<br /><br />To perform a Test, the character attempting the action must roll dice(at least one, but typically several), and will suceed or fail the action based on the results of the dice roll. The number of dice the character rolls is determined by their Attributes, Skills, and additional magical effects. Tests are indicated by values within brackets. To determine the number of dice rolled, resolve any math within the brackets, then roll that many dice. Most Tests call for a relevant Skill and Attribute to be rolled, written [Skill + Attribute]. For these tests, add together the character's Ratings in the Skill and Attribute, and roll that many dice. When the dice are rolled, take note of each die that lands on a 7 or higher. Each such die is a "Hit", and to find the total result of the roll you count up the total number of Hits rolled. To succeed on a Test, the number of Hits rolled on the Test must succeed the Threshold(TH) of the Test. The Threshold for a Test is either determined by the difficulty of the task the character is attempting.  </p>
		</div>
		</div>
		</div>
	</div>
  )
}

export default Introduction